# This is a basic workflow to help you get started with Actions

name: Push Modules to ACR

# Controls when the workflow will run
on:
  # Triggers the workflow on push of tags
  push:
    tags: 
      - 'v*'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Azure login
      - uses: Azure/login@v1.1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Push modules
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az bicep install
            for filename in `ls *.bicep`; do  az bicep publish --file $filename --target br:michaelburch101.azurecr.io/bicep/modules/`basename $filename .bicep`:${{github.ref_name}}; done